spring:
#  本地
  datasource:
      ydprint:
        url: jdbc:mysql://172.16.0.5:3306/yd_print?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&rewriteBatchedStatements=TRUE&useSSL=false
        username: root
        password:
        driver-class-name: com.mysql.jdbc.Driver
        max-active: 500
        initial-size: 1
        max-wait: 5000
        min-idle: 1
        max-idle: 50
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        validation-query: SELECT 'x'
        test-on-borrow: false
        test-while-idle: true
        test-on-return: false
        remove-abandoned: true
        remove-abandoned-timeout: 180
        log-abandoned: true
# 测试
#  datasource:
#      yd_print:
#        url: jdbc:mysql://rm-m5es173x596iii9x0.mysql.rds.aliyuncs.com:3306/yd_print_c?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF8&useSSL=false
#        username: yinle2017
#        password: Yinle2017
#        driver-class-name: com.mysql.jdbc.Driver
#        max-active: 500
#        initial-size: 1
#        max-wait: 5000
#        min-idle: 1
#        max-idle: 50
#        time-between-eviction-runs-millis: 60000
#        min-evictable-idle-time-millis: 300000
#        validation-query: SELECT 'x'
#        test-on-borrow: false
#        test-while-idle: true
#        test-on-return: false
#        remove-abandoned: true
#        remove-abandoned-timeout: 180
#        log-abandoned: true
# 正式
#  datasource:
#      yd_print:
#        url: jdbc:mysql://rm-m5es173x596iii9x0.mysql.rds.aliyuncs.com:3306/yd_print?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF8&useSSL=false
#        username: yinleprint
#        password: Yunding@!2017
#        driver-class-name: com.mysql.jdbc.Driver
#        max-active: 500
#        initial-size: 1
#        max-wait: 5000
#        min-idle: 1
#        max-idle: 50
#        time-between-eviction-runs-millis: 60000
#        min-evictable-idle-time-millis: 300000
#        validation-query: SELECT 'x'
#        test-on-borrow: false
#        test-while-idle: true
#        test-on-return: false
#        remove-abandoned: true
#        remove-abandoned-timeout: 180
#        log-abandoned: true
#mybatis:
#  type-aliases-package: com.yunding.upload.entity

server:
  port: 8080
  undertow:
    io-threads: 16
    worker-threads: 1000
    buffer-size: 1024
    direct-buffers: true

netty:
  port: 11111